
server:
  port: 8080
  
spring:
  application:
    name: gateway-api

zuul:
  ignoredPatterns: /**/admin/**
  prefix: /api

  routes:
    # api: /api/**
    customer-by-service:
      path: /s/customer/**
      service-id: customer-service
    customer-by-ip:
      path: /ip/customer/**
      url: http://${CUSTOMER_SERVICE_IP:192.168.110.113}:8082/
    customer-by-domain:
      path: /nm/customer/**
      url: http://${CUSTOMER_SERVICE_DOMAIN:local.services.vm}:${CUSTOMER_SERVICE_PORT:8082}/

    product-by-service:
      path: /s/product/**
      service-id: product-service 
    product-by-ip:
      path: /ip/product/**
      url: http://${PRODUCT_SERVICE_IP:192.168.110.113}:8083/
    product-by-domain:
      path: /nm/product/**
      url: http://${PRODUCT_SERVICE_DOMAIN:local.services.vm}:${PRODUCT_SERVICE_PORT:8083}/

    proxy-service: 
      path: /mc/**
      service-id: cluster-api

    static:
      path: /static/**


eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  # support to resolve service-id 
  client:
    serviceUrl:
      defaultZone: http://${DISCOVERY_SERVICE_DOMAIN:localhost}:8761/eureka/
